import { galmartAdapter } from './galmart.js';
import type { RetailerAdapter } from './types.js';

export const activeRetailerAdapters: RetailerAdapter[] = [galmartAdapter];

export const retailerResearchRegistry = [
  {
    id: 'galmart',
    name: 'Galmart',
    integrationStatus: 'active',
    verdict: 'YELLOW',
    eanSupport: 'confirmed',
    priceSupport: 'confirmed',
    storeSpecific: false,
    citySpecific: true,
    notes: 'Public city-level catalog lookup works by EAN/GTIN; branch and source update time are not returned.',
  },
  {
    id: 'magnum',
    name: 'Magnum',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: 'partial',
    citySpecific: true,
    notes: 'Official public catalog API exposes products, prices, cities and shops, but a public EAN→product mapping was not confirmed.',
  },
  {
    id: 'small',
    name: 'SMALL',
    integrationStatus: 'research',
    verdict: 'RED',
    eanSupport: 'partner_only',
    priceSupport: 'partner_only',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Official site points to delivery partners for the live catalog. Partner pages can expose GTIN and price, but automated reuse is not approved for production.',
  },
  {
    id: 'metro',
    name: 'METRO Kazakhstan',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Official online catalog is tied to a selected store and exposes price/availability, but public EAN lookup was not confirmed.',
  },
  {
    id: 'anvar',
    name: 'ANVAR',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: 'unknown',
    citySpecific: true,
    notes: 'Official online store exposes a large catalog and prices; deterministic public EAN lookup was not confirmed.',
  },
  {
    id: 'toimart',
    name: 'Toimart',
    integrationStatus: 'research',
    verdict: 'RED',
    eanSupport: 'unconfirmed',
    priceSupport: 'promo_only',
    storeSpecific: false,
    citySpecific: true,
    notes: 'Public promo prices exist, but EAN mapping was not found and Astana is not confirmed in the official store list used in research.',
  },
  {
    id: 'ayan',
    name: 'Ayan Market',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'product_pages',
    priceSupport: 'confirmed_catalog',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Public product pages expose EAN-like article values, current price and a selected seller/store, but a stable public EAN search endpoint was not confirmed.',
  },
  {
    id: 'arbuz',
    name: 'Arbuz.kz',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: false,
    citySpecific: true,
    notes: 'Public city catalogs expose current prices; public barcode mapping was not confirmed.',
  },
  {
    id: 'fixprice',
    name: 'Fix Price Kazakhstan',
    integrationStatus: 'research',
    verdict: 'RED',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Official catalog is city/store aware, but automated access is protected and a public EAN mapping was not confirmed.',
  },
  {
    id: 'carefood',
    name: 'Carefood',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Public catalog and prices are visible for the Carefood hypermarket in Almaty; public EAN mapping was not confirmed.',
  },
  {
    id: 'firkan24',
    name: 'Firkan24',
    integrationStatus: 'research',
    verdict: 'YELLOW',
    eanSupport: 'unconfirmed',
    priceSupport: 'confirmed_catalog',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Public storefront supports store selection and displays product prices; barcode mapping was not confirmed.',
  },
  {
    id: 'astore',
    name: 'A-Store',
    integrationStatus: 'research',
    verdict: 'RED',
    eanSupport: 'unconfirmed',
    priceSupport: 'catalog_partial',
    storeSpecific: true,
    citySpecific: true,
    notes: 'Official online catalog exists for supported cities, but public EAN lookup was not confirmed and Astana is not in the current city selector.',
  },
] as const;

export function getRetailerAdapter(id: string) {
  return activeRetailerAdapters.find((adapter) => adapter.id === id) ?? null;
}
